// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCaZRMl0OTN5CVmdkyhF-nFWI50W4wVWs',
    appId: '1:637824654855:web:2d04fb145c1fa9366a54a2',
    messagingSenderId: '637824654855',
    projectId: 'new-sms-test',
    authDomain: 'new-sms-test.firebaseapp.com',
    storageBucket: 'new-sms-test.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj3Q2hc5a6hQmiX76Kjz8wSIboD4AFkX0',
    appId: '1:637824654855:android:9a6184cf9e1e710a6a54a2',
    messagingSenderId: '637824654855',
    projectId: 'new-sms-test',
    storageBucket: 'new-sms-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlCYJrOw7hJFikSH6Cacv7sqYHrMU7C7c',
    appId: '1:637824654855:ios:ccb5ca998ef8cf506a54a2',
    messagingSenderId: '637824654855',
    projectId: 'new-sms-test',
    storageBucket: 'new-sms-test.appspot.com',
    iosClientId: '637824654855-r3gvkci63dquefq7ogd7vt06neqguaem.apps.googleusercontent.com',
    iosBundleId: 'com.example.smsTest',
  );
}
